fullstorydev/grpcui

- Makefile
Accidentally left a `make` target that makes no sense (at least not yet -- only `grpcurl` has goreleaser configuration).
Also, copy-pasta'ed over a typo.
> fix typo; remove target that does not make sense

- Dockerfile
- cmd/grpcui/grpcui.go
bind was always 127.0.0.1 which made this very hard to work with from docker and kubernetes, this small change should fix it, added a Dockerfile, too but happy enough to remove it if you don't want it.
> make bind address configurable, add dockerfile

- Dockerfile
Previous PR (#10) added the Dockerfile. But it's not quite the shape we want for an "official" Dockerfile in the repo. For now, we'll go without in this repo and add one later once we have a better idea for what we want the image to look like. (The one being removed uses Go as its base image, which means the resulting image is a bit heavy-weight, including the Go SDK which is not necessary for grpcui at runtime.)
> remove Dockerfile for now

- cmd/grpcui/grpcui.go
- cmd/grpcui/unix.go
Effectively adds three new flags to grpcui
* `-unix`, to support communicating with servers listening on a unix domain socket (this is a bug fix: this flag was supposed to be present before but was incorrectly omitted)
* `-max-time`, to support a deadline for all RPC invocations (it applies per RPC request)
* `-max-msg-sz`, to support changing the gRPC library's default limit of 4 megabytes for received response messages.
This branch also tweaks the implementation for two other flags, `-connect-timeout` and `-keepalive-time`: they now use `flags.Float64` instead of using `flags.String` and having to parse (`strconv.ParseFloat`) the value.
This fixes #17 and #18.
> fix -unix flag; add -max-time and -max-msg-sz flags

- .travis.yml
- Makefile
also removed `unused` target since that tool now reports itself deprecated and superseded by `staticcheck`
> staticcheck no longer works with Go 1.10

- handlers.go
Binary metadata values (in response headers and trailers) were transmitted to web client with binary values, which might not be rendered correctly if the value included whitespace and/or control characters. They should be base64-encoded.
> base64-encode bin headers

- internal/resources/webform/webform.js
Fixes #27 
When the web form validates entry of 64-bit signed ints, the logic was simply broken and would not accept any negative values, unless they were actually *less* than the supposed minimum (whoops).
> fix range validation for 64-bit signed ints

- methods.go
When getting all services exposed by a server via reflection,
it is assumed the user does not want to include the reflection
service itself.
> Skip reflection service when getting services via reflection

- go.mod
- go.sum
Among other things, the new version includes some fixes/improvements to JSON and text marshaling for dynamic messages.
https://github.com/jhump/protoreflect/releases/tag/v1.3.0
This fixes #32.
> use just-released v1.3.0 protoreflect

- cmd/grpcui/grpcui.go
The ServerReflection service is not useful through grpcui and is often just noise -- especially if it sorts to the top of the service list and then ends up being the default service selection when opening the UI.
> omit ServerReflection from service list

- .travis.yml
1.9 and 1.10 are ancient and even App Engine no longer supports them.
1.13 and 1.14 are the new hotness.
> drop 1.9 and 1.10; add 1.13 and 1.14

- .travis.yml
Previously, the vet step was done with modules turned off. This allowed versions of dependencies to be unpinned and pick up newer versions that include newer deprecations. The deprecations made vet unhappy.
This pins the deps during the vet step because we are not at this time intending to move to the new protobuf API (though the old one has now been deprecated). We'll move to the new APIs before too long, but it's a non-trivial amount of work and there are other deps which still use the old API...
> vet with modules

- .goreleaser.yml
- Dockerfile
#69 pins a newer version of goreleaser. This fixes the config to work with that newer version. It also updates the Dockerfile so that we use Go 1.13 to build the official image.
> fix goreleaser config; use Go 1.13 in docker build

- .travis.yml
- go.mod
- go.sum
I'm not sure why this suddenly started breaking with Go 1.11.
Maybe related to the fact that, for some reason I cannot determine, the `go` tool keeps wanting to upgrade the `predeclared` tool?
So this also updates the `go.mod` file to reflect that upgrade and also includes associated `go.sum` changes.
> fix CI again... use Go 1.13 to run vet tools

- Dockerfile
With Go 1.11, the Go SDK shipped with only non-module binaries for the standard library. So building something with modules required re-building the standard library, which required having GCC and some other tools installed.
But with Go 1.13, the module versions of the standard libs are included. So we can now skip this step in setting up the Docker container for building grpcui using modules.
> tweak Dockerfile: no need to install gcc to build modules w/ go 1.13

- files.go
- methods.go
- standalone/standalone.go
- testing/cmd/testsvr/test.pb.go
This updates the APIs to allow an interface instead of a concrete struct for the gRPC connection, in the same fashion that gRPC itself relaxed the types in its APIs and generated code.
Also, re-generate testsvr protos.
> use grpc.ClientConnInterface instead of *grpc.ClientConn

- cmd/grpcui/grpcui.go
- go.mod
- go.sum
Fixes #101.
I had originally hoped to address this with changes in the underlying `grpcurl.BlockingDial` function. And I even submitted a change to that function. However, after trying it out, I discovered that the change did not actually work -- there are other issues with `BlockingDial` that cause it to fail fast, and they are not easy to resolve, especially in a backwards-compatible way.
So I instead had to fork the dialing logic since what we want here is just completely different from `BlockingDial` -- it is very much focused on the interactive use case, and has several places that cause it to intentionally fail-fast (with as good of an error message as possible, since the error returned from `grpc.DialContext` can be bad and can obscure underlying connection error messages).
So this …
> Ability to have grpcui not fail-fast on connection errors

- handlers.go
Since we're not validating inputs, users can provide an absurdly large timeout. This can overflow an int64 when it is converted to nanoseconds. So cap off the value at `math.MaxInt64`.
> Cap of input timeout at MaxInt64

- cmd/grpcui/grpcui.go
- handlers.go
- internal/log.go
- standalone/opts.go
- standalone/standalone.go
- webform.go
This adds several command-line options to `grpcui` that are already available in `grpcurl`:
* `-H`, `-rpc-header`: These allow adding extra metadata to all requests, _in addition to_ what the user enters in the web form UI. The difference is that `-H` headers will _also_ be added to reflection requests.
*  `-expand-headers`: This allows for safe use of secrets in metadata by putting them in environment variables instead of on the command-line
* `-use-reflection`: This allows using both server reflection _and_ proto sources, which can be useful to add extra descriptors that the server may not know about for resolving extensions and `google.protobuf.Any` messages.
This also adds a new, related option:
* `-preserve-header`: This allows for propagating headers from the invocation request …
> reconcile grpcui cmd-line options with grpcurl

- Makefile
Previously on an ancient version, which couldn't support M1 MBPs (darwin/arm64).
> use newer goreleaser

- go.mod
- go.sum
- testing/cmd/testsvr/testsvr.go
Previous change to testsvr to include source info in its protos in reflection service used unreleased (and now deleted) `srcinforeflection` package. As of actual release (v1.12.0 of github.com/jhump/protoreflect), there is a different way to accomplish this.
> change testsvr's source info stuff to use latest

- go.mod
- go.sum
Changes to `go.mod` and `go.sum` that result from running:
```shell
go get -u golang.org/x/sys
```
This update is to support running `go install github.com/fullstorydev/grpcui/cmd/grpcui@latest` when using Go 1.18.
> fix: update golang.org/x/sys to support Go 1.18

- cmd/grpcui/grpcui.go
The documentation describe the `-H` option as 
> ...These headers will also be included in reflection requests to a server....
This PR make sure they are passed to the RPC reflection call
> fix: add -H headers argument to reflection request

- cmd/grpcui/grpcui.go
> Open browser in separate goroutine since misbehaving impls can block indefinitely.

- internal/resources/webform/webform-sample.css
- internal/resources/webform/webform.js
I often want to set a timestamp field to the current time, and have to do that manually.
This PR adds a button next to the `google.protobuf.Timestamp` fields to set the timestamp to the current UTC time (based on the browser's time).
> Add a "Now" button for timestamp

- Dockerfile
If I use the `-it` flags with `docker run`, the tool realizes it's in interactive mode, so it tries to open a browser. But that doesn't work from inside a container.
Here's the error I see:
```
Failed to open browser: exec: "xdg-open": executable file not found in $PATH
```
It's not a fatal error, so the tool still works. It's just a nuisance error in the output. This one-liner should remedy that.
> Don't try to open browser when running in Docker

- README.md
Added installation instruction using `homebrew` since its the easiest and fastest, and less prone to errors as well.
> Add installation instruction for homebrew

- internal/resources/webform/webform.js
Grpcurl command was missing headers parameters. This PR adds it.
> feat: add headers to grpcurl command

- go.mod
- go.sum
- protoreflect upgraded to v1.15.3, which addresses this panic
> SIGSEGV: panic: runtime error: invalid memory address or nil pointer dereference in protoreflect

- Makefile
This PR disables CGO so we don't have any dependencies on C libraries expected to be found in the environment, in order to achieve a better compatibility across distros.
Tested by running `make install` before and after the changes and inspecting the produced binary from a Linux machine (Debian in this case).
**Before**
```sh
ldd $(which grpcui)
linux-vdso.so.1 (0x00007ffe2cb2e000)
libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007fcc13946000)
libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fcc13924000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fcc13750000)
/lib64/ld-linux-x86-64.so.2 (0x00007fcc1396a000)
```
**After**
```sh
ldd $(which grpcui)
not a dynamic executable
```
Follow-up of the same changes in `grpcurl`: …
> Disable CGO for improved compatibility across distros

- releasing/README.md
- releasing/do-release.sh
While releasing `grpcurl@v1.8.9`, I encountered an error described in https://github.com/fullstorydev/grpcurl/pull/421.
A similar change happened in `grpcui`'s Homebrew formula: https://github.com/Homebrew/homebrew-core/commit/c845f04a193ac8b5a03004ddc763aad23e1d8eca
We probably need to update the Tarball URL used to update our Homebrew formula as well.
> Update Tarball URL used by Homebrew

- README.md
- cmd/grpcui/grpcui.go
- files.go
- methods.go
- testing/cmd/testsvr/testsvr.go
Currently, `grpc.reflection.v1.ServerReflection` is shown in the list of `Service Name`. This PR removes it as well as `grpc.reflection.v1alpha.ServerReflection`.
Also, change to use `v1` protocol if we can use it.
> Support `grpc.reflection.v1.ServerReflection`

- .goreleaser.yml
The `archives.replacements` field from the `goreleaser` configuration file was [removed](https://goreleaser.com/deprecations/#archivesreplacements).
It's stopping us from releasing a new version:
```
goreleaser release --clean
• starting release...
⨯ release failed after 0s                  error=yaml: unmarshal errors:
line 25: field replacements not found in type config.Archive
```
The suggested alternative is to use `archives.name_template`.
Tested by running `goreleaser release --skip publish` locally, inspecting the built archive names, and comparing them to past releases:
```
• archives
• creating                                       archive=dist/grpcui_1.4.2_linux_x86_32.tar.gz
• creating                                       archive=dist/grpcui_1.4.2_windows_x86_64.zip
• creating …
```
> Replace removed goreleaser archives.replacements configuration

- .circleci/config.yml
- Makefile
Some of our static check tools were too old and didn't work with Go >= 1.20.
This PR bumps the versions of those tools so they can work with the current latest Go version (1.23) and runs the full set of CI checks on that version.
> Run full set of checks using Go 1.23

- go.mod
- go.sum
Updating the `grpcurl` version to the latest release (https://github.com/fullstorydev/grpcurl/releases/tag/v1.9.3) before releasing `grpcui` itself.
> Bump grpcurl dependency version to v1.9.3

- cmd/grpcui/grpcui.go
This fixes filtering services or methods to expose using the -service or -method option.
Note that in line 878 the processed config is deleted from the passed configs map. This lets the len(configs) != 0 check in line 874 fail for all following services. This results in exposing more services than expected.
> Fix filtering services or methods to expose

- internal/resources/webform/webform.js
updateJSONRequest already calls the function with the object converted to a json string. No need to double call it, the second time with the raw object
Probably a simpler version of https://github.com/fullstorydev/grpcui/pull/340
> Remove double updateCurlCommand call
